export const CLASS = {
  APP: '.js-app',
  MONEY_FORM: '.js-money-form',
  MONEY: '.js-money',
  LOTTO_HEADER: '.js-lotto-detail-header',
  LOTTO_COUNT: '.js-lotto-count',
  TOGGLE_NUMBERS: '.js-toggle-numbers',
  LOTTO_LIST: '.js-lotto-detail-list',
  WINNING_FORM: '.js-winning-form',
  WINNING_NUMBERS_CONTAINER: '.js-winning-number-container',
  WINNING_BONUS_CONTAINER: '.js-winning-bonus-container',
  WINNING_STATISTICS_INFO: '.js-winning-statistics-info',
  WINNING_STATISTICS_RATE: '.js-winning-statistics-rate',
  MODAL: '.js-modal',
  OPEN_MODAL: '.js-open-result-modal-button',
  CLOSE_MODAL: '.js-modal-close',
  RETRY: '.js-retry',
};
