const LOTTO_MAX_VALUE = 45
const LOTTO_MIN_VALUE = 1
const LOTTO_BALL_AMOUNT = 7 //6개를 추첨한 뒤
const LOTTO_RESULT_AMOUNT = 6 //6개를 추첨한 뒤
const LOTTO_RESULT_BONUS = 1 //그 후 보너스 1개를 추첨
const PRICE_FOR_ONE = 1000 // 개당 금액

export {
	LOTTO_MAX_VALUE, LOTTO_MIN_VALUE, LOTTO_BALL_AMOUNT, 
	LOTTO_RESULT_AMOUNT, LOTTO_RESULT_BONUS, PRICE_FOR_ONE
}