export const LOTTO_PRICE_PER_UNIT = 1000;
export const LOTTO_NUMBER_COUNT_PER_UNIT = 6;
export const MIN_LOTTO_NUMBER = 1;
export const MAX_LOTTO_NUMBER = 45;

export const LOTTO_RANKING = {
    FIRST: 'FIRST',
    SECOND: 'SECOND',
    THIRD: 'THIRD',
    FOURTH: 'FOURTH',
    FIFTH: 'FIFTH',
    ETC: 'ETC',
};
export const LOTTO_WINNING_AMOUNT = {
    [LOTTO_RANKING.FIRST]: 2000000000,
    [LOTTO_RANKING.SECOND]: 30000000,
    [LOTTO_RANKING.THIRD]: 1500000,
    [LOTTO_RANKING.FOURTH]: 50000,
    [LOTTO_RANKING.FIFTH]: 5000,
    [LOTTO_RANKING.ETC]: 0,
};
