const RULES = {
  MIN_TICKET_NUMBER: 1,
  MAX_TICKET_NUMBER: 45,
  MIN_LOTTO_PURCHASE_PRICE: 1000,
  MAX_LOTTO_PURCHASE_PRICE: 100_000,
  TICKET_PRICE: 1000,
  TICKET_LENGTH: 6,
  WINNING_PERSON_INITIAL: 1,
  WINNING_PERSON_PLUS: 1,
};

export default RULES;
