import { lottoModule } from '../../src/js/modules/lottoModule';
import { LOTTO_PER_PRICE, MATCHED_NUMBERS } from '../../src/js/consts';

export const TEST_TICKET_NUMBER = 5;
const FIRST_INDEX = 0;

describe('lottoModule test', () => {
  let autoGeneratedNumbersSet;
  const { buyAllLottoByCount, getTicketNumbersOfBuying, getWinningResult } =
    lottoModule(LOTTO_PER_PRICE * TEST_TICKET_NUMBER);

  beforeEach(() => {
    const ticketNumbers = getTicketNumbersOfBuying(LOTTO_PER_PRICE);
    autoGeneratedNumbersSet = buyAllLottoByCount(ticketNumbers);
  });
  it('단일 기본 당첨숫자를 알아낼 수 있다.', () => {
    const winningNumbers = autoGeneratedNumbersSet[FIRST_INDEX].slice();
    const result = getWinningResult(winningNumbers, autoGeneratedNumbersSet);
    expect(result).includes(MATCHED_NUMBERS.SIX);
  });

  it('보너스 기본 당첨숫자를 알아낼 수 있다.', () => {
    const winningNumbers = autoGeneratedNumbersSet[FIRST_INDEX].slice();
    const bonusNumber = winningNumbers[winningNumbers.length - 1] + 1;
    autoGeneratedNumbersSet[FIRST_INDEX][
      autoGeneratedNumbersSet[FIRST_INDEX].length - 1
    ] = bonusNumber;
    const result = getWinningResult(
      winningNumbers,
      autoGeneratedNumbersSet,
      bonusNumber
    );
    expect(result).includes(MATCHED_NUMBERS.FIVE_WITH_BONUS);
  });
});
