export const ERROR_CODES = {
  ERROR_DUPLICATE_NUMBER: "ERROR_DUPLICATE_NUMBER",
  ERROR_INVALID_LENGTH: "ERROR_INVALID_LENGTH",
  ERROR_INVALID_NUMBER: "ERROR_EMPTY_INPUT_LEN",
  ERROR_UNKOWN: "ERROR_UNKOWN",
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.ERROR_DUPLICATE_NUMBER]: "로또 번호는 중복되지 않습니다.",
  [ERROR_CODES.ERROR_INVALID_LENGTH]: "로또 번호는 6자리입니다.",
  [ERROR_CODES.ERROR_INVALID_NUMBER]: "로또 번호는 1~45 자연수입니다.",
  [ERROR_CODES.ERROR_UNKOWN]: "알 수 없는 오류가 발생했습니다.",
};
