const MAX_RANDOM_NUMBER = 45;

const MAX_COUNT_PER_LOTTO = 6;

const PRICE_PER_LOTTO = 1000;

const INITIAL_AMOUNT = 0;

export { MAX_RANDOM_NUMBER, MAX_COUNT_PER_LOTTO, PRICE_PER_LOTTO, INITIAL_AMOUNT };
