import { SELECTOR_ID, SELECTOR_CLASS, SELECTOR_CY } from './selector.js';

import {
	MAX_RANDOM_NUMBER,
	MAX_LOTTO_NUMBER,
	MIN_LOTTO_NUMBER,
	MAX_COUNT_PER_LOTTO,
	PRICE_PER_LOTTO,
	FIFTH_PLACE,
	FORTH_PLACE,
	THIRD_PLACE,
	SECOND_PLACE,
	FIRST_PLACE,
	MAX_WINNING_NUMBERS_LENGTH,
} from './magicNumber.js';

import {
	NOT_TEN_UNIT_PRICE_MESSAGE,
	UNDER_MIN_NUMBER_MESSAGE,
	OVER_MAX_NUMBER_MESSAGE,
	DUPLICATE_NUMBER_MESSAGE,
	INPUT_AMOUNT_MESSAGE,
	NOT_EMPTY_WINNING_NUMBERS_MESSAGE,
} from './validatorMessage.js';

export {
	MAX_RANDOM_N
	MAX_LOTTO_NUMBER,
	MIN_LOTTO_NUMBER,
	MAX_COUNT_PER_LOTTO,
	MAX_WINNING_NUMBERS_LENGTH,
	PRICE_PER_LOTTO,
	FIFTH_PLACE,
	FORTH_PLACE,
	THIRD_PLACE,
	SECOND_PLACE,
	FIRST_PLACE,
	SELECTOR_ID,
	SELECTOR_CLASS,
	SELECTOR_CY,
	NOT_TEN_UNIT_PRICE_MESSAGE,
	UNDER_MIN_NUMBER_MESSAGE,
	OVER_MAX_NUMBER_MESSAGE,
	DUPLICATE_NUMBER_MESSAGE,
	INPUT_AMOUNT_MESSAGE,
	NOT_EMPTY_WINNING_NUMBERS_MESSAGE,
};
