const LOTTO_PER_PRICE = 1000;
const LOTTO_TRY_COUNT = 6;
const LOTTO_NUMBER_RANGE = 42;
const LOTTO_NUMBERS = Array.from(
  { length: LOTTO_NUMBER_RANGE },
  (_, i) => i + 1
);

const BONUS_WEIGHT = 0.5;
const MATCHED_NUMBERS = {
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  FIVE_WITH_BONUS: 5 + BONUS_WEIGHT,
  SIX: 6,
};
const PRIZE_MONEY = {
  [MATCHED_NUMBERS.THREE]: 2_000,
  [MATCHED_NUMBERS.FOUR]: 50_000,
  [MATCHED_NUMBERS.FIVE]: 1_500_000,
  [MATCHED_NUMBERS.FIVE_WITH_BONUS]: 30_000_000,
  [MATCHED_NUMBERS.SIX]: 2_000_000_000,
};
export {
  LOTTO_PER_PRICE,
  LOTTO_TRY_COUNT,
  LOTTO_NUMBERS,
  MATCHED_NUMBERS,
  BONUS_WEIGHT,
  PRIZE_MONEY,
};
