export const DEFAULT_PRICE = 1000;
export const LOTTERY_COUNT = 6;
export const RANGE = 45;

export const EVENT = {
  INPUT_PRICE: "INPUT_PRICE",
  TOGGLE_LOTTERY_NUMBERS: "TOGGLE_LOTTERY_NUMBERS",
  RETRY: "RETRY",
  CLOSE_RESULT_MODAL: "CLOSE_RESULT_MODAL",
};
