export const LOTTO_RANK_RULES = {
  FIRST: 6,
  SECOND: 5,
  THIRD: 5,
  FOURTH: 4,
  FIFTH: 3,
};

export const LOTTO_RANK_MONEY = {
  FIRST: 2000000000,
  SECOND: 30000000,
  THIRD: 1500000,
  FOURTH: 50000,
  FIFTH: 5000,
};

export const TICKET_PRICE = 1000;

export const LOTTO_RANK = {
  FIRST: 1,
  SECOND: 2,
  THIRD: 3,
  FOURTH: 4,
  FIFTH: 5,
};

export const LOTTO_RANK_KEY_REVERSE = {
  1: "FIRST",
  2: "SECOND",
  3: "THIRD",
  4: "FOURTH",
  5: "FIFTH",
};

export const PRISE_LOOKUP_TABLE = {
  [LOTTO_RANK.FIRST]: LOTTO_RANK_MONEY.FIRST,
  [LOTTO_RANK.SECOND]: LOTTO_RANK_MONEY.SECOND,
  [LOTTO_RANK.THIRD]: LOTTO_RANK_MONEY.THIRD,
  [LOTTO_RANK.FOURTH]: LOTTO_RANK_MONEY.FOURTH,
  [LOTTO_RANK.FIFTH]: LOTTO_RANK_MONEY.FIFTH,
};

export const RANK_MAPPING_LOOKUP_TABLE = {
  [LOTTO_RANK_RULES.FIRST]: LOTTO_RANK.FIRST,
  [LOTTO_RANK_RULES.SECOND]: {
    true: LOTTO_RANK.SECOND,
    false: LOTTO_RANK.THIRD,
  },
  [LOTTO_RANK_RULES.FOURTH]: LOTTO_RANK.FOURTH,
  [LOTTO_RANK_RULES.FIFTH]: LOTTO_RANK.FIFTH,
};
