export const SET_PRICE = 'SET_PRICE';
export const SET_PURCHASED_LOTTO_NUMBERS = 'SET_LOTTO_NUMBERS';
export const SET_PURCHASED_LOTTO_BONUS_NUMBER =
  'SET_PURCHASED_LOTTO_BONUS_NUMBER';
export const SET_WIN_LOTTO_NUMBER = 'SET_WIN_LOTTO_NUMBER';
export const RESTART = 'RESTART';
