export const COMMIT = {
  SET_AMOUNT: 'SET_AMOUNT',
  SET_LOTTO_LIST: 'SET_LOTTO_LIST',
  SET_IS_VISIBLE_LOTTOS: 'SET_IS_VISIBLE_LOTTOS',
  SET_WON_LOTTO: 'SET_WON_LOTTO',
  SET_BONUS_NUMBER: 'SET_BONUS_NUMBER',
};

export const DISPATCH = {
  MAKE_LOTTO_LIST: 'MAKE_LOTTO_LIST',
  RESTART_LOTTO: 'RESTART_LOTTO',
};

export const GETTER = {
  LOTTO_AMOUNT: 'LOTTO_AMOUNT',
};
