export const { DISPLAY_NONE, MANUAL_LOTTO_NUMBER, MANUAL_LOTTO_NUMBER_CONTAINNER } = Object.freeze({
  DISPLAY_NONE: 'd-none',
  MANUAL_LOTTO_NUMBER_CONTAINNER: 'MANUAL_LOTTO_NUMBER_CONTAINNER',
  MANUAL_LOTTO_NUMBER: 'MANUAL_LOTTO_NUMBER',
})
