const TITLE_SELECTOR = '.title';
const MONEY_INPUT_SELECTOR = '.money-input';
const MONEY_INPUT_BUTTON_SELECTOR = '.money-input-button';
const TICKET_SELECTOR = '.ticket';
const TICKET_NOTICE_SELECTOR = '.ticket-notice';
const TICKET_NUMBERS_SELECTOR = '.ticket-numbers';
const TICKET_TOGGLE_BUTTON_SELECTOR = '.ticket-toggle-button';
const PRICE = 1000;
const MAX_NUMBER = 45;
const MIN_NUMBER = 1;
const NUMBER_AMOUNT = 6;
const UPPER_LIMIT_MONEY = 100000;
const LOWER_LIMIT_MONEY = 1000;
const MIN_WINNING_COUNT = 3;
const FIVE_PLUS_BONUS = '5+bonus';
const NOT_DIVISIBLE_MONEY_BY_THOUSAND_TEXT =
  '로또 구입 금액을 1,000 단위로 입력해 주세요.';
const NOT_UPPER_THAN_LOWER_LIMIT = '값은 1000 이상이어야 합니다.';
const NOT_LOWER_THAN_UPPER_LIMIT = '값은 100000 이하여야 합니다.';

export {
  TITLE_SELECTOR,
  MONEY_INPUT_SELECTOR,
  MONEY_INPUT_BUTTON_SELECTOR,
  TICKET_SELECTOR,
  TICKET_NOTICE_SELECTOR,
  TICKET_NUMBERS_SELECTOR,
  TICKET_TOGGLE_BUTTON_SELECTOR,
  PRICE,
  MAX_NUMBER,
  MIN_NUMBER,
  NUMBER_AMOUNT,
  UPPER_LIMIT_MONEY,
  LOWER_LIMIT_MONEY,
  MIN_WINNING_COUNT,
  FIVE_PLUS_BONUS,
  NOT_LOWER_THAN_UPPER_LIMIT,
  NOT_DIVISIBLE_MONEY_BY_THOUSAND_TEXT,
  NOT_UPPER_THAN_LOWER_LIMIT,
};
