const PRICE = 1000;
const MAX_NUMBER = 45;
const MIN_NUMBER = 1;
const NUMBER_AMOUNT = 6;
const UPPER_LIMIT_MONEY = 100000;
const LOWER_LIMIT_MONEY = 1000;

export {
  PRICE,
  MAX_NUMBER,
  MIN_NUMBER,
  NUMBER_AMOUNT,
  UPPER_LIMIT_MONEY,
  LOWER_LIMIT_MONEY,
};
