const LOTTO_REWARD_CODE = Object.freeze({
  FIRST: 'MATCH_6',
  SECOND: 'MATCH_5_WITH_BONUS',
  THIRD: 'MATCH_5',
  FOURTH: 'MATCH_4',
  FIFTH: 'MATCH_3',
});

const LOTTO_PRIZE_TABLE = Object.freeze({
  [LOTTO_REWARD_CODE.FIRST]: 2_000_000_000,
  [LOTTO_REWARD_CODE.SECOND]: 30_000_000,
  [LOTTO_REWARD_CODE.THIRD]: 1_500_000,
  [LOTTO_REWARD_CODE.FOURTH]: 50_000,
  [LOTTO_REWARD_CODE.FIFTH]: 5_000,
});

export { LOTTO_PRIZE_TABLE, LOTTO_REWARD_CODE };
