export const LOTTO_NUMBER_SIZE = 6;
export const LOTTO_BONUS_MATCHED_SIZE = 5;
export const LOTTO_MAX_RANGE = 45;
export const LOTTO_PURCHASE_UNIT = 1000;
export const LOTTO_PURCHASE_MAX_PRICE = 100000;
export const LOTTO_PURCHASE_MAX_QUANTITY = 100;
