import { LOTTO_PRICE } from "../domain/constant.js";

const VALID_NUMBER_REQUIRED = "VALID_NUMBER_REQUIRED";
const LOTTO_MIN_PRICE_REQUIRED = "LOTTO_MIN_PRICE_REQUIRED";
const LOTTO_LENGTH_REQUIRED = "LOTTO_LENGTH_REQUIRED";
const DUPLICATE_NOT_ALLOWED = "DUPLICATE_NOT_ALLOWED";
const ALLOWED_YES_NO = "y/n 둘중 하나만 선택하세요";

const ERROR_MESSAGE = Object.freeze({
  [VALID_NUMBER_REQUIRED]: VALID_NUMBER_REQUIRED,
  [LOTTO_MIN_PRICE_REQUIRED]: `${LOTTO_MIN_PRICE_REQUIRED}: ${LOTTO_PRICE.PRICE}원 이상`,
  [LOTTO_LENGTH_REQUIRED]: LOTTO_LENGTH_REQUIRED,
  [DUPLICATE_NOT_ALLOWED]: DUPLICATE_NOT_ALLOWED,
  [ALLOWED_YES_NO]: ALLOWED_YES_NO,
});

export {
  ERROR_MESSAGE,
  VALID_NUMBER_REQUIRED,
  LOTTO_MIN_PRICE_REQUIRED,
  LOTTO_LENGTH_REQUIRED,
  DUPLICATE_NOT_ALLOWED,
  ALLOWED_YES_NO,
};
