export const PRICE_OF_LOTTO = 1000;
export const NUM_OF_LOTTO_NUMBERS = 6;
export const MIN_LOTTO_NUM = 1;
export const MAX_LOTTO_NUM = 45;

export const notifyTypes = {
  BUY_LOTTIES: "BUY_LOTTIES",
  TOGGLE_SHOW_LOTTIES_NUMBERS: "TOGGLE_SHOW_LOTTIES_NUMBERS",
  SHOW_LOTTIE_WINNING_INFO: "SHOW_LOTTIE_WINNING_INFO",
  RESET_LOTTIE_GAME: "REST_LOTTIE_GAME",
};

export const winningTypes = {
  ALL: "ALL",
  FIVE_WITH_BONUS: "FIVE_WITH_BONUS",
  FIVE: "FIVE",
  FOUR: "FOUR",
  THREE: "THREE",
};

export const winningMoney = {
  ALL: 2000000000,
  FIVE_WITH_BONUS: 30000000,
  FIVE: 1500000,
  FOUR: 50000,
  THREE: 5000,
};
